version: '3'

services:
    db:
        image: mysql:5.7
        restart: always
        command: --disable-partition-engine-check
        environment:
            MYSQL_ROOT_USER: ${DB_USER}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DATABASE}
        ports:
            - '3306:3306'
        volumes:
            - ./db:/var/lib/mysql
        networks:
            - mysql-compose-network

    adminer:
        image: adminer
        ports:
            - 8080:8080
        networks:
            - mysql-compose-network

networks:
    mysql-compose-network:
        driver: bridge
